apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-rollout
  template:
    metadata:
      labels:
        app: example-rollout
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 50
      - pause:
          duration: 10m # 1 hour
      - setWeight: 100
      - pause: {} # pause indefinitely

